services:
  clinic-appointment:
    container_name: clinic-appointment
    build:
      context: ./appointment
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    networks:
      - clinic-network

  clinic-doctor:
    container_name: clinic-doctor
    build:
      context: ./doctor
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    environment:
      AUI_PROJ_APPOINTMENT_URL: "http://clinic-appointment:8081"
    networks:
      - clinic-network

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      AUI_PROJ_APPOINTMENT_URL: "http://clinic-appointment:8081"
      AUI_PROJ_DOCTOR_URL: "http://clinic-doctor:8082"
      AUI_PROJ_GATEWAY_HOST: "api-gateway:8080"
    networks:
      - clinic-network

  clinic-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clinic-frontend
    restart: always
    environment:
      API_URL: "http://api-gateway:8080/api"
    ports:
      - "4200:80"
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge