services:
  clinic-appointment:
    build:
      context: ./appointment
      dockerfile: Dockerfile
    restart: always

  clinic-doctor:
    build:
      context: ./doctor
      dockerfile: Dockerfile
    restart: always
    environment:
      AUI_PROJ_DOCTOR_URL: "http://clinic-doctor:8080"

  clinic-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    environment:
      AUI_PROJ_APPOINTMENT_URL: "http://clinic-appointment:8080"
      AUI_PROJ_DOCTOR_URL: "http://clinic-doctor:8080"
      AUI_PROJ_GATEWAY_HOST: "clinic-gateway:8080"

  clinic-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      API_URL: http://clinic-gateway:8080/api
    ports:
      - "8087:80"