version: '3'

services:
  aui-proj-appointment:
    build:
      context: ./AUI-PROJ-APPOINTMENT
      dockerfile: Dockerfile
    restart: always

  aui-proj-doctor:
    build:
      context: ./AUI-PROJ-DOCTOR
      dockerfile: Dockerfile
    restart: always
    environment:
      AUI_PROJ_DOCTOR_URL: "http://aui-proj-doctor:8080"

  aui-proj-gateway:
    build:
      context: ./AUI-PROJ-GATEWAY
      dockerfile: Dockerfile
    restart: always
    environment:
      AUI_PROJ_APPOINTMENT_URL: "http://aui-proj-appointment:8080"
      AUI_PROJ_DOCTOR_URL: "http://aui-proj-doctor:8080"
      AUI_PROJ_GATEWAY_HOST: "aui-proj-gateway:8080"

  aui-proj-angular:
    build:
      context: ./AUI-PROJ-ANGULAR
      dockerfile: Dockerfile
    restart: always
    environment:
      API_URL: http://aui-proj-gateway:8080/api
    ports:
      - "8087:80"