### Get all appointments

GET http://localhost:8081/api/appointments

### Get single appointment

GET http://localhost:8081/api/appointments/2f02ee92-a7f6-4dac-9226-8092c68e697e

### Get single appointment, not existing

GET http://localhost:8081/api/appointments/a25e5c24-672e-4aea-b6f9-ec9c72cc023f

### Get doctor appointments

GET http://localhost:8081/api/doctors/4d64923b-24d6-4505-8af2-c197730fc574/appointments

### Get doctor appointments, not existing

GET http://localhost:8081/api/doctors/a25e5c24-672e-4aea-b6f9-ec9c72cc023f/appointments

### Create new appointment

PUT http://localhost:8081/api/appointments/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "patientName": "Maciej Maćkowy",
  "patientAge" : 25,
  "doctorId": "213e95d5-5103-48be-8f74-fc149d604790"
}

### Delete appointment.

DELETE http://localhost:8081/api/appointments/4a2348e4-8a9f-47b4-8987-5c0c875cc5de

### Get all doctors

GET http://localhost:8081/api/doctors

### Get single doctor

GET http://localhost:8081/api/doctors/1f54b7d6-ba12-4561-87b3-7b6deaab951f

### Get single doctor, not existing

GET http://localhost:8081/api/doctors/ac4e2683-b2ba-4695-94d9-806a97fce71e

### Delete doctor

DELETE http://localhost:8081/api/doctors/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76


